### ISSUE TITLE
ClassCastException: io.filepicker.models.Node cannot be cast to io.filepicker.models.Provider 

### ISSUE THREAD

**Issue by lifalzarano** [filestack/filestack-android#122] opened 2017-06-27 19:04 UTC
We've been getting this issue intermittently since upgrading to 4.0.1:

     java.lang.ClassCastException: io.filepicker.models.Node cannot be cast to io.filepicker.models.Provider
        1 at io.filepicker.Filepicker.checkStoragePermission (Filepicker.java:337)
        2 at io.filepicker.Filepicker.onStart (Filepicker.java:350)

**Comment by shawnmaten** [comment] 2017-08-10 16:32
Could you provide more info on when you see this? And if possible, explicit steps to reproduce it?

**Comment by dembrats** [comment] 2017-08-24 00:09
It appears to happen after loading saved state.  I think because Provider doesn't override writeToParcel().

**Comment by shawnmaten** [comment] 2017-12-21 18:18
Closing this as it's no longer relevant for v2.

**Closed by shawnmaten** 2017-12-21 18:18 UTC
